first
Idatiev-Vladimir/SpringREST-task-3.1.3 pull request #1
Opened 2023-09-12 17:30 UTC by Idatiev

spring rest task 3.1.3

2023-09-12 22:48 UTC, pdasilem requested changes

2023-09-12 22:48 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminRestController.java
> +    private static void checkUserNotFoundExc(BindingResult bindingResult) {
убери это из контроллера

2023-09-12 22:48 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/AdminRestController.java
> +    private ResponseEntity<UserErrorResponse> handlerException(UserNotFoundException e) {
никаких методов хэндлеров в контроллере

2023-09-12 22:48 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +@Setter
выпилить ломбок полностью из проекта

2023-09-13 08:50 UTC, Idatiev commented
Редактировал

2023-09-14 06:22 UTC, pdasilem approved these changes

2023-09-14 07:31 UTC, merged